### ISSUE TITLE
Pyroclasm mod instantly crashes the game, during launcher boot process

### ISSUE THREAD

**Issue by sazuko07** [grondag/Pyroclasm#25]
throws error of "failed to load class pyroclasm.pyroclasm". This mod no longer works.

**Comment by grondag** [comment]
This mod does indeed no longer work and older version are no longer supported.  Sadly.  I will be released an updated version someday.

**Comment by oriolprogamer712** [comment]
It has been 5 years since you said that and there is still nothing, no release for versions 1.14, 1.16, 1.17, or 1.18 fabric oh forge.
